// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/publishers": {
    params: {};
  };
  "/publishers/:slug": {
    params: {
      "slug": string;
    };
  };
  "/series/:sqid/:slug": {
    params: {
      "sqid": string;
      "slug": string;
    };
  };
  "/comic/:id": {
    params: {
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/publishers" | "/publishers/:slug" | "/series/:sqid/:slug" | "/comic/:id";
  };
  "./Layout.tsx": {
    id: "Layout";
    page: "/" | "/publishers" | "/publishers/:slug" | "/series/:sqid/:slug" | "/comic/:id";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/publishers.tsx": {
    id: "routes/publishers";
    page: "/publishers";
  };
  "routes/publishers.$slug.tsx": {
    id: "routes/publishers.$slug";
    page: "/publishers/:slug";
  };
  "routes/SeriesDetails.tsx": {
    id: "routes/SeriesDetails";
    page: "/series/:sqid/:slug";
  };
  "routes/comic.$id.tsx": {
    id: "routes/comic.$id";
    page: "/comic/:id";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "Layout": typeof import("./app/./Layout.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/publishers": typeof import("./app/routes/publishers.tsx");
  "routes/publishers.$slug": typeof import("./app/routes/publishers.$slug.tsx");
  "routes/SeriesDetails": typeof import("./app/routes/SeriesDetails.tsx");
  "routes/comic.$id": typeof import("./app/routes/comic.$id.tsx");
};