// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/publishers": {
    params: {};
  };
  "/publishers/:slug": {
    params: {
      "slug": string;
    };
  };
  "/series/:sqid/:slug": {
    params: {
      "sqid": string;
      "slug": string;
    };
  };
  "/comic/:sqid/:slug": {
    params: {
      "sqid": string;
      "slug": string;
    };
  };
  "/login": {
    params: {};
  };
  "/logout": {
    params: {};
  };
  "/comic/:sqid/page/:page": {
    params: {
      "sqid": string;
      "page": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/publishers" | "/publishers/:slug" | "/series/:sqid/:slug" | "/comic/:sqid/:slug" | "/login" | "/logout" | "/comic/:sqid/page/:page";
  };
  "./Layout.tsx": {
    id: "Layout";
    page: "/" | "/publishers" | "/publishers/:slug" | "/series/:sqid/:slug" | "/comic/:sqid/:slug";
  };
  "routes/Home.tsx": {
    id: "routes/Home";
    page: "/";
  };
  "routes/Publishers.tsx": {
    id: "routes/Publishers";
    page: "/publishers";
  };
  "routes/PublisherDetails.tsx": {
    id: "routes/PublisherDetails";
    page: "/publishers/:slug";
  };
  "routes/SeriesDetails.tsx": {
    id: "routes/SeriesDetails";
    page: "/series/:sqid/:slug";
  };
  "routes/ComicDetails.tsx": {
    id: "routes/ComicDetails";
    page: "/comic/:sqid/:slug";
  };
  "./AuthLayout.tsx": {
    id: "AuthLayout";
    page: "/login";
  };
  "routes/Login.tsx": {
    id: "routes/Login";
    page: "/login";
  };
  "routes/Logout.tsx": {
    id: "routes/Logout";
    page: "/logout";
  };
  "routes/ComicPage.tsx": {
    id: "routes/ComicPage";
    page: "/comic/:sqid/page/:page";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "Layout": typeof import("./app/./Layout.tsx");
  "routes/Home": typeof import("./app/routes/Home.tsx");
  "routes/Publishers": typeof import("./app/routes/Publishers.tsx");
  "routes/PublisherDetails": typeof import("./app/routes/PublisherDetails.tsx");
  "routes/SeriesDetails": typeof import("./app/routes/SeriesDetails.tsx");
  "routes/ComicDetails": typeof import("./app/routes/ComicDetails.tsx");
  "AuthLayout": typeof import("./app/./AuthLayout.tsx");
  "routes/Login": typeof import("./app/routes/Login.tsx");
  "routes/Logout": typeof import("./app/routes/Logout.tsx");
  "routes/ComicPage": typeof import("./app/routes/ComicPage.tsx");
};